# 모델 아키텍처 설정
small_model:
  vocab_size: 50000
  d_model: 512
  n_heads: 8
  n_layers: 6
  d_ff: 2048
  max_seq_len: 1024
  dropout: 0.1

medium_model:
  vocab_size: 50000
  d_model: 768
  n_heads: 12
  n_layers: 12
  d_ff: 3072
  max_seq_len: 2048
  dropout: 0.1

large_model:
  vocab_size: 50000
  d_model: 1024
  n_heads: 16
  n_layers: 24
  d_ff: 4096
  max_seq_len: 4096
  dropout: 0.1